Repository MultiCoreNetwork/carpet-redcraft-addons, pull requests merged in 2021-03, with the labels that each got.

#9 Fix iron_axe TreeCapitator trade percentage
  src/main/resources/assets/carpet-redcraft-addons/scripts/morewanderingtrades.sc
Labels: bug, ready to merge

#11 LastDeathCompass replaces last slot of hotbar
  src/main/resources/assets/carpet-redcraft-addons/scripts/lastdeathcompass.sc
Labels: bug, ready to merge

#20 Added /playerme script
  README.md
  README_IT.md
  src/main/java/it/multicoredev/carpetredcraftaddons/CarpetRedCraftExtension.java
  src/main/java/it/multicoredev/carpetredcraftaddons/CarpetRedCraftSettings.java
  src/main/resources/assets/carpet-redcraft-addons/scripts/playerme.sc
Labels: bug, ready to merge

#23 Added killed_by, dropped and crafted in /stats
  src/main/resources/assets/carpet-redcraft-addons/scripts/stats.sc
Labels: bug, ready to merge

#24 fastRedstoneCrafting
  README.md
  README_IT.md
  src/main/java/it/multicoredev/carpetredcraftaddons/CarpetRedCraftExtension.java
  src/main/java/it/multicoredev/carpetredcraftaddons/CarpetRedCraftSettings.java
  src/main/resources/assets/carpet-redcraft-addons/datapacks/RedPack - Fast Redstone Crafting.zip
Labels: ready to merge, suggestion

#25 brickAndPrismarineBackCrafting
  README.md
  README_IT.md
  src/main/java/it/multicoredev/carpetredcraftaddons/CarpetRedCraftExtension.java
  src/main/java/it/multicoredev/carpetredcraftaddons/CarpetRedCraftSettings.java
  src/main/resources/assets/carpet-redcraft-addons/datapacks/RedPack - BrickAndPrismarine Back Crafting.zip
Labels: invalid, suggestion

#27 AI and NOAI nametags are inverted
  src/main/resources/assets/carpet-redcraft-addons/scripts/specialnametags.sc
Labels: bug, ready to merge

#29 Invisible Item Frames drop normal Item Frames
  src/main/resources/assets/carpet-redcraft-addons/scripts/invisibleitemframe.sc
Labels: bug, ready to merge

#41 Wrong blockstate of trapdoors
  src/main/resources/assets/carpet-redcraft-addons/scripts/placeableplants.sc
Labels: bug

#35 Fixed Spelling error
  src/main/resources/assets/carpet-redcraft-addons/scripts/stats.sc
Labels: bug

#43 Added moss.sc
  .gitignore
  README.md
  README_IT.md
  src/main/java/it/multicoredev/carpetredcraftaddons/CarpetRedCraftExtension.java
  src/main/java/it/multicoredev/carpetredcraftaddons/CarpetRedCraftSettings.java
  src/main/resources/assets/carpet-redcraft-addons/scripts/moss.sc
Labels: suggestion

#42 Added Craftable Sculk Sensor
  .gitignore
  README.md
  README_IT.md
  src/main/java/it/multicoredev/carpetredcraftaddons/CarpetRedCraftExtension.java
  src/main/java/it/multicoredev/carpetredcraftaddons/CarpetRedCraftSettings.java
  src/main/resources/assets/carpet-redcraft-addons/datapacks/RedPack - Craftable Sculk Sensor/RedPack - Craftable Sculk Sensor.zip
  src/main/resources/assets/carpet-redcraft-addons/datapacks/RedPack - Craftable Sculk Sensor/data/global/advancements/root.json
  src/main/resources/assets/carpet-redcraft-addons/datapacks/RedPack - Craftable Sculk Sensor/data/minecraft/tags/functions/load.json
  src/main/resources/assets/carpet-redcraft-addons/datapacks/RedPack - Craftable Sculk Sensor/data/redpack/advancements/craftable_sculk_sensor/craftable_sculk_sensor.json
  src/main/resources/assets/carpet-redcraft-addons/datapacks/RedPack - Craftable Sculk Sensor/data/redpack/advancements/craftable_sculk_sensor/recipes/sculk_sensor.json
  src/main/resources/assets/carpet-redcraft-addons/datapacks/RedPack - Craftable Sculk Sensor/data/redpack/advancements/crafting.json
  src/main/resources/assets/carpet-redcraft-addons/datapacks/RedPack - Craftable Sculk Sensor/data/redpack/advancements/redpack.json
  src/main/resources/assets/carpet-redcraft-addons/datapacks/RedPack - Craftable Sculk Sensor/data/redpack/functions/sculk_sensor_crafting/main.mcfunction
  src/main/resources/assets/carpet-redcraft-addons/datapacks/RedPack - Craftable Sculk Sensor/data/redpack/functions/sculk_sensor_crafting/setup.mcfunction
  src/main/resources/assets/carpet-redcraft-addons/datapacks/RedPack - Craftable Sculk Sensor/data/redpack/functions/sculk_sensor_crafting/uninstall.mcfunction
  src/main/resources/assets/carpet-redcraft-addons/datapacks/RedPack - Craftable Sculk Sensor/data/redpack/recipes/sculk_sensor.json
  src/main/resources/assets/carpet-redcraft-addons/datapacks/RedPack - Craftable Sculk Sensor/data/redpack/tags/functions/sculk_sensor_crafting/load.json
  src/main/resources/assets/carpet-redcraft-addons/datapacks/RedPack - Craftable Sculk Sensor/data/redpack/tags/functions/sculk_sensor_crafting/loop.json
  src/main/resources/assets/carpet-redcraft-addons/datapacks/RedPack - Craftable Sculk Sensor/pack.mcmeta
  src/main/resources/assets/carpet-redcraft-addons/datapacks/RedPack - Craftable Sculk Sensor/pack.png
Labels: ready to merge, suggestion

#50 Azalea Tree
  README.md
  README_IT.md
  src/main/java/it/multicoredev/carpetredcraftaddons/CarpetRedCraftExtension.java
  src/main/java/it/multicoredev/carpetredcraftaddons/CarpetRedCraftSettings.java
  src/main/resources/assets/carpet-redcraft-addons/scripts/azaleatree.sc
  src/main/resources/assets/carpet-redcraft-addons/scripts/morewanderingtrades.sc
Labels: ready to merge, suggestion
